### ISSUE TITLE
在ios11下没有调起摄像头

### ISSUE THREAD

**Issue by xfd213** [macrine/qrscanner#1]
在ios11下没有调起摄像头，指出现了动画，请问如何解决，谢谢！

**Comment by macrine** [comment]
已经修复，替换下文件就行

**Comment by xfd213** [comment]
thank you!


________________________________
发件人: mac <notifications@github.com>
发送时间: 2018年6月19日 4:22
收件人: macrine/qrscanner
抄送: xfd213; Author
主题: Re: [macrine/qrscanner] 在ios11下没有调起摄像头 (#1)


已经修复，替换下文件就行

―
